### PR TITLE
React 18 support

### PR DESCRIPTION
**Pull request by rstacruz**
Thanks [lreddickGNA](https://github.com/lreddickGNA) for starting this with #80! This is a re-implementation of his PR to add React 18 support, but without removing the custom adapter support.

### CODE REVIEW

**Review by lreddickGNA — APPROVED** [review]

**Comment by lreddickGNA** [comment]
@rstacruz awesome stuff! When do you think I new version will be published to npm?

**Comment by rstacruz** [comment]
Unfortunately I'm having trouble with my npm account at the moment so I'm not sure :(

**Comment by rstacruz** [comment]
Btw, caveat - React 18 stopped supporting IE11, so the next Remount will not support IE11.

There's still code in Remount to support IE11 for now, simply because we haven't had a chance to remove them yet. Presumably we'll be removing those bits as we go.

**Comment by rstacruz** [comment]
Published a pre-release as `remount@0.12.0-0` (or `remount@next`), give it a try! Just a few checks, then I'll publish it under the *latest* tag @lreddickGNA @jekku 

EDIT: now out as remount@1.0.0 - https://github.com/rstacruz/remount/releases/tag/v1.0.0

**Comment by lreddickGNA** [comment]
@rstacruz awesome! I will update our project package json to reflect the new release!

**Pull request merged**
