### PR TITLE
[React 18] Update to be compatible.

### PR DESCRIPTION
**Pull request by lreddickGNA**
Updating `ReactDOM.render` to the new `createRoot` function specified in the React 18 upgrade. 

This PR only updates `custom_elements.js` which is what I'm using in my Rails application. Work still needs to be done for `mutation_obersver.js`

### CODE REVIEW

**Comment by rstacruz** [comment]
Thanks, I was really having trouble getting React 18 to work myself. Is this ready for review?

**Comment by lreddickGNA** [comment]
@rstacruz At least the implementation of this so far works for my production build. I couldn't get the testing to work locally- and I believe the testing would also need an update. But it's more or less ready for review.

**Comment by lreddickGNA** [comment]
Yea it looks like you'd want to update `mutation_observer.js` since `onUnmount` and `onUpdate` events are used in there and I'm no longer taking the mountPoint as a parameter... instead you need to pass the root object.

**Comment by rstacruz** [comment]
Thanks for this! I'll try to look into this when I have time -- one thing we will need to update is all documentation.

**Comment by rstacruz** [comment]
Interesting - looks like the way this works is it creates a hard dependency on React, and prevents implementing [custom adapters for non-React frameworks](https://github.com/rstacruz/remount/blob/master/docs/api.md#custom-adapters).

I think that might be alright - I'm not sure if anyone uses Remount in that way (would love to hear if anyone knows!) and we may have to remove that feature altogether.

(...either that, or implement it in a way that doesn't change the signature of custom adapters)

**Comment by rstacruz** [comment]
There's also a few tests that might need to be updated - looks like the *.html tests still reference react@16 :thinking:

**Comment by rstacruz** [comment]
Also it looks like the shadow DOM workarounds [provided in react-shadow-dom-retarget-events](https://www.npmjs.com/package/react-shadow-dom-retarget-events) will no longer be needed :)

**Comment by rstacruz** [comment]
Thanks for your contribution! I continued it on a bit over at #81 - hopefully it should be a bit more comprehensive :)

**Comment by lreddickGNA** [comment]
Closing since this has been moved to https://github.com/rstacruz/remount/pull/81

**Comment by rstacruz** [comment]
React 18 support is now out in remount@1.0.0 - https://github.com/rstacruz/remount/releases/tag/v1.0.0

**Pull request closed without merging**
